import * as fs from 'fs';
import {isProduction} from "./environment";

/**
 * This module is a server-only module that loads up the manifests for js, css & images from dist/ folder
 */

let revManifest;

if (isProduction()) {
    // If we are in production, we are then loading the manifests from the dist directory (generated by gulp)
    revManifest = {
        js: JSON.parse(fs.readFileSync("dist/rev-manifest-js.json", "utf8")),
        css: JSON.parse(fs.readFileSync("dist/rev-manifest-css.json", "utf8")),
        img: JSON.parse(fs.readFileSync("dist/rev-manifest-images.json", "utf8"))
    };
} else {
    // On dev, we don't use any manifests => the original files from the build directory will be used
    revManifest = {
        js: {},
        css: {},
        img: {}
    }
}

/**
 * Returns the combined manifest that we loaded up in memory
 */
export function getManifest() {
    return revManifest;
}
